doc: Add README.md
StiVit/cautious-waddle pull request #1
Opened 2024-06-08 17:33 UTC by StiVit

2024-06-10 12:19 UTC, grumpycatyo-collab commented on test.db
Make sure the `test.db` is also in the .gitignore files. You will need it locally only.

2024-06-10 12:20 UTC, StiVit commented on test.db
🫡

2024-06-12 19:19 UTC, grumpycatyo-collab commented on run.py
I guess this uvicorn part should be in the `main.py`. From my point of view `run.py` is not the correct naming. Also you should move the `main.py` outside. I mean, it shouldn't be inside the `app` folder.

2024-06-12 19:23 UTC, grumpycatyo-collab requested changes

2024-06-12 19:23 UTC, grumpycatyo-collab commented on run.py
So basically your `main.py` should be looking like this:
```
import uvicorn
from fastapi import FastAPI
from app.database import engine, Base
from app.routers import items

Base.metadata.create_all(bind=engine)
# FastAPI app instance
app = FastAPI()


# Include routers
app.include_router(items.router, prefix="/api", tags=["items"])

if __name__ == "__main__":
    uvicorn.run("app.main:app", host = "127.0.0.1", port=8000, reload=True)
```

2024-06-12 19:30 UTC, grumpycatyo-collab commented on README.md
Update the documentation with your updates ( how the API works )

2024-06-12 19:30 UTC, grumpycatyo-collab commented on app/models.py
The implementation with the `Item` model is good, however we need something more advanced, that's why I'd recommend to change the `Item` model towards the `User` model, and add some fields. Don't forget make changes in `schemas.py` and also other files where your model is mentioned

2024-06-17 10:37 UTC, grumpycatyo-collab approved these changes

2024-06-20 08:42 UTC, merged